#!/bin/bash

python main/train_runner.py \
--MODEL_VERSION=v3 \
--ALL_DATASET=/all_dataset \
--BATCH_SIZE=64 \
--TEST_SIZE=1500 \
--NUMBER_EPOCHS=20 \
--EMBEDDING_SIZE=200 \
--CONV0_DROPOUT=0.3 \
--CONV1_DROPOUT=0.3 \
--CONV0_NUMBER_FILTERS=100 \
--CONV1_NUMBER_FILTERS=10 \
--FC0_SIZE=100 \
--CONV0_KERNEL_FILTER_SIZE=5 \
--CONV1_KERNEL_FILTER_SIZE=5 \
--FC0_DROPOUT=0.3 \
--FC1_DROPOUT=0.3
