#!/bin/bash

python main/train_runner.py \
--MODEL_VERSION=v2 \
--ALL_DATASET=/all_dataset \
--BATCH_SIZE=64 \
--TEST_SIZE=1500 \
--NUMBER_EPOCHS=20 \
--EMBEDDING_SIZE=200 \
--CONV0_DROPOUT=0.5 \
--CONV1_DROPOUT=0.5 \
--CONV0_NUMBER_FILTERS=10 \
--CONV1_NUMBER_FILTERS=10 \
--FC0_SIZE=50

python main/train_runner.py \
--MODEL_VERSION=v2 \
--ALL_DATASET=/all_dataset \
--BATCH_SIZE=64 \
--TEST_SIZE=1500 \
--NUMBER_EPOCHS=20 \
--EMBEDDING_SIZE=200 \
--CONV0_DROPOUT=0.5 \
--CONV1_DROPOUT=0.5 \
--CONV0_NUMBER_FILTERS=10 \
--CONV1_NUMBER_FILTERS=10 \
--FC0_SIZE=10

python main/train_runner.py \
--MODEL_VERSION=v2 \
--ALL_DATASET=/all_dataset \
--BATCH_SIZE=512 \
--TEST_SIZE=1500 \
--NUMBER_EPOCHS=20 \
--EMBEDDING_SIZE=200 \
--CONV0_DROPOUT=0.5 \
--CONV1_DROPOUT=0.5 \
--CONV0_NUMBER_FILTERS=10 \
--CONV1_NUMBER_FILTERS=10 \
--FC0_SIZE=10
